# Generated by Django 5.2.1 on 2025-05-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyView', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='grace_period',
            field=models.IntegerField(default=15, help_text='Grace period in minutes after start time'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='absent', max_length=10),
        ),
    ]
