# Generated by Django 5.2.1 on 2025-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyView', '0002_attendancesession_grace_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='session_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
